// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
  queries: { key: 'products'; input: never; result: Products[] };
  mutations: never;
  subscriptions: never;
};

export type Products = {
  id: string;
  name: string;
  description: string;
  price: number;
  stock: number;
  image: string;
  created_at: string | null;
  updated_at: string | null;
  deleted_at: string | null;
};
