// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "carts.get", input: never, result: Cart } | 
        { key: "products.get", input: never, result: Product[] } | 
        { key: "users.get", input: never, result: Customers | null },
    mutations: 
        { key: "carts.remove", input: string, result: null } | 
        { key: "carts.update", input: UpdateCartArgs, result: ProductCarts } | 
        { key: "orders.checkout", input: Checkout, result: null } | 
        { key: "products.create", input: AddProductArgs, result: Products } | 
        { key: "products.delete", input: string, result: Products } | 
        { key: "products.update", input: UpdateProductArgs, result: Products } | 
        { key: "users.add.address", input: AddAddressArgs, result: Customers },
    subscriptions: never
};

export type ProductCarts = { product_id: string; cart_id: string; quantity: number; total_price: number }

export type Checkout = { courier: string; address: string; payment_method: string }

export type Customers = { id: string; created_at: string | null; updated_at: string | null; username: string; name: string; email: string; address: string | null; phone: string | null }

export type UpdateCartArgs = { product_id: string; quantity: number }

export type Feedback = { id: string; created_at: string | null; updated_at: string | null; deleted_at: string | null; feedback: string; rating: number; product_id: string }

export type ProductCart = { product_id: string; cart_id: string; quantity: number; total_price: number; product: Products }

export type AddAddressArgs = { address: string; phone: string }

export type Reviews = ({ id: string; created_at: string | null; updated_at: string | null; deleted_at: string | null; feedback: string; rating: number; product_id: string }) & { username: string }

export type Product = ({ id: string; name: string; description: string; price: number; stock: number; image: string; created_at: string | null; updated_at: string | null; deleted_at: string | null }) & { reviews: Reviews[] }

export type UpdateProductArgs = { id: string; name: string; description: string; price: number; stock: number }

export type AddProductArgs = { name: string; description: string; price: number; stock: number; image: string }

export type Cart = { id: string; total_price: number; product_carts: ProductCart[] }

export type Products = { id: string; name: string; description: string; price: number; stock: number; image: string; created_at: string | null; updated_at: string | null; deleted_at: string | null }
