// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "carts.get", input: never, result: CartResponse } | 
        { key: "products.get", input: never, result: Product[] },
    mutations: 
        { key: "carts.update", input: UpdateCartInput, result: ProductCarts } | 
        { key: "products.create", input: AddProduct, result: Products } | 
        { key: "products.delete", input: string, result: Products } | 
        { key: "products.update", input: EditProduct, result: Products },
    subscriptions: never
};

export type Product = ({ id: string; name: string; description: string; price: number; stock: number; image: string; created_at: string | null; updated_at: string | null; deleted_at: string | null }) & { reviews: Reviews[] }

export type UpdateCartInput = { product_id: string; quantity: number }

export type Feedback = { id: string; created_at: string | null; updated_at: string | null; deleted_at: string | null; feedback: string; rating: number; product_id: string }

export type ProductCart = ({ product_id: string; cart_id: string; quantity: number; total_price: number }) & { product: Products }

export type ProductCarts = { product_id: string; cart_id: string; quantity: number; total_price: number }

export type Products = { id: string; name: string; description: string; price: number; stock: number; image: string; created_at: string | null; updated_at: string | null; deleted_at: string | null }

export type AddProduct = { name: string; description: string; price: number; stock: number; image: string }

export type Reviews = ({ id: string; created_at: string | null; updated_at: string | null; deleted_at: string | null; feedback: string; rating: number; product_id: string }) & { username: string }

export type CartResponse = { id: string; total_price: number; product_carts: ProductCart[] }

export type EditProduct = { id: string; name: string; description: string; price: number; stock: number }
